### ISSUE TITLE
Can't I skip the training step?

### ISSUE THREAD

**Issue by sch0722** [alenzenx/TrackNetV3#2]
Dear author,
I hope this email finds you well. I am currently working with your video processing scripts for my project. First and foremost, I want to express my gratitude for providing such a valuable resource.

However, I have encountered a couple of issues while running the scripts, and I would greatly appreciate your guidance in resolving them.

1. Error in `denoise.py`:
When executing the `denoise.py` script, I encountered the following error:
<details><summary>Details</summary>
<p>
Traceback (most recent call last):
  File "C:\Users\Hank\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'X'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "denoise.py", line 557, in <module>
    smooth(os.path.join(rootdir, 'pred_result', i))
  File "denoise.py", line 9, in smooth
    x = df['X'].tolist()
  File "C:\Users\Hank\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\Hank\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'X'

</p>
</details> 

2.Error in `predict.py`:
When running the `predict.py` script with a test video consisting of 935 frames (possibly a multiple of 5), I encountered the following error:
```python
935
Number of sampled frames: 0
Number of sampled frames: 15
Number of sampled frames: 30
Number of sampled frames: 45
Number of sampled frames: 60
Number of sampled frames: 75
Number of sampled frames: 90
Number of sampled frames: 105
Number of sampled frames: 120
Number of sampled frames: 135
Number of sampled frames: 150
Number of sampled frames: 165
Number of sampled frames: 180
Number of sampled frames: 195
Number of sampled frames: 210
Number of sampled frames: 225
Number of sampled frames: 240
Number of sampled frames: 255
Number of sampled frames: 270
Number of sampled frames: 285
Number of sampled frames: 300
Number of sampled frames: 315
Number of sampled frames: 330
Number of sampled frames: 345
Number of sampled frames: 360
Number of sampled frames: 375
Number of sampled frames: 390
Number of sampled frames: 405
Number of sampled frames: 420
Number of sampled frames: 435
Number of sampled frames: 450
Number of sampled frames: 465
Number of sampled frames: 480
Number of sampled frames: 495
Number of sampled frames: 510
Number of sampled frames: 525
Number of sampled frames: 540
Number of sampled frames: 555
Number of sampled frames: 570
Number of sampled frames: 585
Number of sampled frames: 600
Number of sampled frames: 615
Number of sampled frames: 630
Number of sampled frames: 645
Number of sampled frames: 660
Number of sampled frames: 675
Number of sampled frames: 690
Number of sampled frames: 705
Number of sampled frames: 720
Number of sampled frames: 735
Number of sampled frames: 750
Number of sampled frames: 765
Number of sampled frames: 780
Number of sampled frames: 795
Number of sampled frames: 810
Number of sampled frames: 825
Number of sampled frames: 840
Number of sampled frames: 855
Number of sampled frames: 870
Number of sampled frames: 885
Number of sampled frames: 900
Number of sampled frames: 915
Number of sampled frames: 930
Traceback (most recent call last):
  File "predict.py", line 105, in <module>
    assert len(frame_queue) % num_frame == 0
AssertionError
``` 
Is there any assistance or suggestions you could provide would be immensely helpful. Thank you for your time and consideration.

**Comment by alenzenx** [comment]
謝謝您支持我們並幫助我們找出錯誤，這是更新過的檔案，

https://drive.google.com/drive/folders/1jn1cmcEgELgdDwhHxu4FGP5byWGx73ql?usp=sharing

predict.py已經確定修正5的倍數的問題。

denoise.py也已經修正我們測試中出現的問題，但不保證更新後的denoise.py還會不會出現其他問題，因為原始的denoise.py是其他團隊編寫的，如果還有其他問題歡迎提出!

最後，關於可不可以跳過訓練步驟的這個問題，在於您的部署環境是否相似於訓練集，如果部署環境的亮度，陰影，背景顏色跟訓練集相差蠻大的話，建議您還是重新標註及訓練。

Thank you for supporting us and helping us find errors, here is the updated archive,

https://drive.google.com/drive/folders/1jn1cmcEgELgdDwhHxu4FGP5byWGx73ql?usp=sharing

predict.py has fixed the issue with multiples of 5.

denoise.py has also corrected the problems that occurred in our tests, but there is no guarantee that the updated denoise.py will have other problems, because the original denoise.py was written by another team. If you have other problems, please feel free to ask!

Finally, as to whether you can skip the training step, it depends on whether your deployment environment is similar to the training set. If the brightness, shadow, and background color of the deployment environment are quite different from the training set, it is recommended that you re-label and train.

**Comment by sch0722** [comment]
@alenzenx 
Thank you to the author for your timely reply. I have another question below.
```
Frame	Visibility	X	Y
860	1	872	552
860	1	872	552
861	1	890	470
Lack of 862(Total frame=862)
```
It seems like you're encountering an issue with a CSV file generated using a new version of the "predict.py" script. The problem also occasionally occurs with the old version, but it doesn't seem to be a significant issue as it happens sporadically and no clear pattern has been identified yet. The problem involves the occurrence of duplicate frames being saved.
